# Generated by Django 4.1.6 on 2023-05-18 00:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("uuids", models.TextField(max_length=500)),
                ("name", models.CharField(max_length=100)),
                ("thumbnail", models.CharField(max_length=255, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="fk_user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConnectToSocial",
            fields=[
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.IntegerField()),
                ("type", models.SmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("thumbnail", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="fk_user_id",
                        help_text="그룹 소유주",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("updated_at", models.DateTimeField(auto_created=True, auto_now=True)),
                ("created_at", models.DateTimeField(auto_created=True, auto_now=True)),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("contents", models.TextField(null=True)),
                (
                    "group_id",
                    models.ForeignKey(
                        db_column="fk_group_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="damoim_service.group",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="fk_user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PostToImage",
            fields=[
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("image_url", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post_id",
                    models.ForeignKey(
                        db_column="fk_post_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="damoim_service.post",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LikeToPost",
            fields=[
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "post_id",
                    models.ForeignKey(
                        db_column="fk_post_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="damoim_service.post",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="fk_user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupToUser",
            fields=[
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "group_id",
                    models.ForeignKey(
                        db_column="fk_group_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="damoim_service.group",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="fk_user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommentToPost",
            fields=[
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deleted_at", null=True),
                ),
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment_id",
                    models.ForeignKey(
                        db_column="fk_comment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="damoim_service.comment",
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        db_column="fk_post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="damoim_service.post",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="fk_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
